sprite $gitlab [53x51/4] {
______wlwwww-_-_______________________wlwwwwkt-______
_____wlwggggg-l-_____________________slwgggggwlw_____
____g_gggggggg-hz___________________s_wgggggggwls____
__-R-gggggggggg-hz_________________sVwgggggggggw_s___
_-h-gggggggggggg-h----------------wlwgggggggggggg_h__
-h-ggggggggggggggwwwwwwwwwwwwwwwwwwwgggggggggggggg-h-
lvfgggggggggggggggggggggggggggggggggggggggggggggggfzh
rLLLLLbbffgggggggggggggggggggggggggggggggggffbbLLLLL-
LLLLLLLLLLLbffgggggggggggggggggggggggggfbbLLLLLLLLLLL
VLLLLLLLLLLLLLLbffgggggggggggggggggfbbLLLLLLLLLLLLLL_
qVLLLLLLLLLLLLLLLLLbffgggggggggfbbLLLLLLLLLLLLLLLLNzt
_VtTNLLLLLLLLLLLLLLLLLLbffgfbbLLLLLLLLLLLLLLLLLLNTxV_
____VtjTNLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMNTxtl____
________Vx-TNLLLLLLLLLLLLLLLLLLLLLLLLLLMNTxtV________
____________Vx-TNLLLLLLLLLLLLLLLLLLNNTtxV____________
________________VtyTNLLLLLLLLLLNNTpxV________________
____________________VtyTNLLNNTppV____________________
}

