sprite $gitlab_logo [50x50/4] {
__________________________________________________
__________________________________________________
__________________________________________________
_______________-xx-____________-xx-_______________
_____________-l-ggwlw________wlwgg-l-_____________
____________wlwggggwlw______wlwggggwlw____________
___________sVwgggggg-kkkkkkkk-ggggggwVs___________
__________w_rbffggggggggggggggggggffbr_w__________
__________L_LLLLLLbfggggggggggfbLLLLLL_L__________
__________VtTNLLLLLLLLbfggfbLLLLLLLLNTtV__________
____________lFtTNNLLLLLLLLLLLLLLNNTtFl____________
________________VxxTNNLLLLLLNNTtxV________________
____________________VptSNNStpV____________________
________________________VV________________________
__________________________________________________
__________________________________________________
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
}